# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/buktop/projects/GTK-Paint

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/buktop/projects/GTK-Paint

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buktop/projects/GTK-Paint/CMakeFiles /home/buktop/projects/GTK-Paint//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buktop/projects/GTK-Paint/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PFL

# Build rule for target.
PFL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PFL
.PHONY : PFL

# fast build rule for target.
PFL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/build
.PHONY : PFL/fast

src/Color_buttons.o: src/Color_buttons.c.o
.PHONY : src/Color_buttons.o

# target to build an object file
src/Color_buttons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Color_buttons.c.o
.PHONY : src/Color_buttons.c.o

src/Color_buttons.i: src/Color_buttons.c.i
.PHONY : src/Color_buttons.i

# target to preprocess a source file
src/Color_buttons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Color_buttons.c.i
.PHONY : src/Color_buttons.c.i

src/Color_buttons.s: src/Color_buttons.c.s
.PHONY : src/Color_buttons.s

# target to generate assembly for a file
src/Color_buttons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Color_buttons.c.s
.PHONY : src/Color_buttons.c.s

src/Drawing_events.o: src/Drawing_events.c.o
.PHONY : src/Drawing_events.o

# target to build an object file
src/Drawing_events.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Drawing_events.c.o
.PHONY : src/Drawing_events.c.o

src/Drawing_events.i: src/Drawing_events.c.i
.PHONY : src/Drawing_events.i

# target to preprocess a source file
src/Drawing_events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Drawing_events.c.i
.PHONY : src/Drawing_events.c.i

src/Drawing_events.s: src/Drawing_events.c.s
.PHONY : src/Drawing_events.s

# target to generate assembly for a file
src/Drawing_events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/Drawing_events.c.s
.PHONY : src/Drawing_events.c.s

src/globals.o: src/globals.c.o
.PHONY : src/globals.o

# target to build an object file
src/globals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/globals.c.o
.PHONY : src/globals.c.o

src/globals.i: src/globals.c.i
.PHONY : src/globals.i

# target to preprocess a source file
src/globals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/globals.c.i
.PHONY : src/globals.c.i

src/globals.s: src/globals.c.s
.PHONY : src/globals.s

# target to generate assembly for a file
src/globals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/globals.c.s
.PHONY : src/globals.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/main.c.s
.PHONY : src/main.c.s

src/menu_events.o: src/menu_events.c.o
.PHONY : src/menu_events.o

# target to build an object file
src/menu_events.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/menu_events.c.o
.PHONY : src/menu_events.c.o

src/menu_events.i: src/menu_events.c.i
.PHONY : src/menu_events.i

# target to preprocess a source file
src/menu_events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/menu_events.c.i
.PHONY : src/menu_events.c.i

src/menu_events.s: src/menu_events.c.s
.PHONY : src/menu_events.s

# target to generate assembly for a file
src/menu_events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PFL.dir/build.make CMakeFiles/PFL.dir/src/menu_events.c.s
.PHONY : src/menu_events.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PFL"
	@echo "... src/Color_buttons.o"
	@echo "... src/Color_buttons.i"
	@echo "... src/Color_buttons.s"
	@echo "... src/Drawing_events.o"
	@echo "... src/Drawing_events.i"
	@echo "... src/Drawing_events.s"
	@echo "... src/globals.o"
	@echo "... src/globals.i"
	@echo "... src/globals.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu_events.o"
	@echo "... src/menu_events.i"
	@echo "... src/menu_events.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

